from typing import Annotated, Literal, Optional
from typing_extensions import TypedDict
from langgraph.graph import MessagesState


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# Risk management team state
class RiskDebateState(TypedDict):
    aggressive_history: Annotated[
        str, "Aggressive Agent's Conversation history"
    ]  # Conversation history
    conservative_history: Annotated[
        str, "Conservative Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_aggressive_response: Annotated[
        str, "Latest response by the aggressive analyst"
    ]  # Last response
    current_conservative_response: Annotated[
        str, "Latest response by the conservative analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    asset_type: Annotated[str, "Asset type under analysis such as stock or crypto"]
    instrument_context: Annotated[str, "Deterministic ticker identity resolved at run start"]
    trade_date: Annotated[str, "What date we are trading at"]

    sender: Annotated[str, "Agent that sent this message"]

    # research step
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Sentiment Analyst"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # Phase 2 — structured trade signal + validation
    # Stored as a plain dict (JSON-serialisable) so LangGraph state remains
    # serialisable without embedding Pydantic models directly in TypedDict.
    trade_signal: Annotated[
        Optional[dict],
        "TradeSignal.model_dump() produced by the Trader; None until Trader runs",
    ]
    signal_validation_result: Annotated[
        Optional[dict],
        (
            "Result dict from the Signal Validator: "
            "{'valid': bool, 'forced_no_trade': bool, 'error': str, "
            "'sizing': dict|None, 'ticket': str|None}"
        ),
    ]
    trader_retry_count: Annotated[
        int,
        "Number of times the Trader has been retried by the Signal Validator",
    ]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]
    past_context: Annotated[str, "Memory log context injected at run start (same-ticker decisions + cross-ticker lessons)"]

    # Phase 4 — position management mode
    analysis_mode: Annotated[
        str,
        "Pipeline mode: 'new_trade' (default) or 'manage_position' (reviewing an open position)",
    ]
    open_position: Annotated[
        Optional[dict],
        "Open position dict from PositionStore when analysis_mode='manage_position'; None for new_trade",
    ]
    position_action: Annotated[
        Optional[dict],
        "PositionAction.model_dump() produced by the Position Manager; None until PM runs in manage mode",
    ]
    position_context_block: Annotated[
        str,
        "Formatted position summary block injected into all agents in manage_position mode",
    ]
